name: Create GH Release

on:
  push:
    tags:
      - "v*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy 

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test 

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --all --release 

      - name: Compress archive
        run: tar -cvzf target/release/notes-cli.tar.gz target/release/notes-cli

      - id: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Latest release"
          files: |
            target/release/notes-cli
            target/release/*.tar.gz

      - name: path
        run: echo "${{ steps.release.outputs.upload_url }}"

      - name: tag 
        run: echo "${{ steps.release.outputs.automatic_releases_tag }}"
